server:
  port: ${PORT:8080}

spring:
  application:
    name: StockAtelier

  data:
    mongodb:
      uri: ${MONGO_URI}
      auto-index-creation: true

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: ${GEMINI_MODEL:gemini-2.5-flash}